---
title: "Ch2 Exercises"
author: "Kai Aragaki"
date: "8/25/2020"
output: html_document
---
# Chapter 2 Excercies: Conceptual


## Question 1
For each of parts (a) through (d), indicate weather we would generally expect the performance of a flexible statistical learning method to be better or worse that an inflexible method. Justify your answer.

a. The sample size *n* is extremely large, and the number of predictors *p* is small 

**I'd argue that a more flexible model would win out - with a large enough sample size, you are likely to be able to pick up non-linear trends in the data that would be ignored without a flexible model. More rigorously, we can think about this in terms of bias vs variance tradeoff. Variance is likely to be less of an issue for even moderately flexible methods due to the huge number of samples which likely represent the true population. Conversely, by increasing flexibility, we avoid the pitfall of rigidity that causes bias - essentially deafening ourselves to the trends that huge amounts of data can certainly provide.**

b. The number of predictors p is extremely large, and the number of observations n is small
        
**I would argue that a much more flexible model would be prudent here. Since even a single new observation could change the outcomes drastically, we would want to be resilient to outliers. Something like a linear model or the lasso might be a good choice.**
        
c. The relationship between the predictors and response is highly non-linear

**Inflexible models tend to be linear and thus would not capture the true nature of the response. Something more flexible (a spline???) might be useful.**

d. The variance of the error terms, i.e. $\sigma^2$ = Var($\epsilon$), is extremely high.

**Less flexibility would probably be better, so the model is not subject to the volatile whims of the data**

## Question 2
Explain whether each scenario is a classification or regression problem and indicate whether we are most interested in inference or prediction. Finally, provide *n* and *p*.

a. We collect a set of data on the top 500 firms in the US. For each firm we record profit, number of employees, industry and the CEO salary. We are interested in understanding which factors affect CEO salary.

**This is a regression problem - we are determining the magnitude of the salary. A classification problem might be 'how do we develop a method to determine which CEOs will have a billionaire's salary?'. Additionally, this is an inference problem - we are interested in mechanism, and we want to know which factors affect CEO salary (rather than just getting an output of what their salary would be given factors x, y and z). Finally, *n* is 500 (the number of firms) and *p* is 3 (with CEO as the response variable)**

b. We are considering launching a new product and wish to know whether it will be a success or a failure. We collect data on 20 similar products that were previously launched. For each product we have recorded whether it was a success or failure, price charged for the product, marketing budget, competition price, and ten other variables.

**This is a classification problem - we don't want to know how much of a success our product will be, we just want to know if it will be a success or a failure - black and white, no gray. This is a prediction problem - we are not interested in knowing what makes something a success or failure, we are only concerned with accurately predicting the outcome. Finally, *n* = 20, and *p* = 13, with success or failure as our response variable.**

c. We are interested in predicting the % change in the USD/Euro exchange rate in relation to the weekly changes in the world stock markets. Hence we collect weekly data for all of 2012. For each week we record the % change in the USD/Euro, the % change in the US market, the % change in the British market, and the % change in the German market.

**This is a regression, prediction problem. We have an n = 52, and a p = 3 with one response variable.**


## Question 3
We now revisit the bias-variance decomposition.

a. Provide a sketch of typical (squared) bias, variance, training error, test error, and Bayes (or irreducible) error curves, on a single plot, as we go from less flexible statistical learning methods towards more flexible approaches. The x-axis should represent the amount of flexibility in the method, and the y-axis should represent the values for each curve. There should be five curves. Make sure to label each one.

b. Explain why each of the five curves has the shape displayed in part (a)

**As flexibility increases, bias decreases: more flexibility reduces the chance that we will miss an trend due to our model being too 'biased' in terms of the assumption of its shape**

**As flexibility increases, variance increases: the addition of new datapoints has the potential to change the function quite drastically.**

**The training error continually decreases. As we allow the model to fit the data more and more closely (by increasing 'freedom' or flexibility) it will fit more accurately to our TRAINING set**

**The test error will decrease until it hits the the Bayesian or irreducible error**

**The Bayes error will remain constant through increasing flexibility. It represents "ground truth" error rate, but is also unobtainable as it requires us to know the probability of an outcome for every set of predictors. It is non-zero because there is an overlap between classes that cannot be teased apart**

## Question 4
You will now think of some real-life applications for statistical learning.

a. Describe three real-life application in which classification might be useful. Describe the response, as well as the predictors. Is the goal each application inference or prediction? Explain your answer.

**Determining if a tumor is either 'basal' or 'luminal' by RNAseq. The response could be a sum of canonical basal markers minus the expression of luminal markers. The predictors would be the rest of the genes. This would likely be inferential, as we would want to determine WHAT makes a tumor basal or luminal**

**Whether a given library will fail or not. Response: Library success/failure. Predictors: Kit used, 260/230/280, TapeStation, Concentration, DV200. Prediction is the short term goal but if we can infer what the issue is to increase our odds that would be best.**

**Whether it will rain or not. Response: Rain. Predictors: Wind speed, weather from previous years, current season, if it rained yesterday, temperature. Prediction.**

b